In [90]:
%matplotlib inline

import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [91]:
grid_width = 5
grid_height = 5

actions= np.array([[-1,0], [1, 0], [0, -1], [0, 1]])
state_A = np.array([1, 0])
state_B = np.array([3, 0])
state_A_prime = np.array([1, grid_height-1])
state_B_prime = np.array([3, 2])

reward_offset = 0
reward_any = 0 + reward_offset
reward_out = -1 + reward_offset
reward_A = 10 + reward_offset
reward_B = 5 + reward_offset
gamma = 0.9
prob_policy = 1. / len(actions)

n_limit = 1e-3

In [104]:
# figure 3.5
num_steps = 100
values_prime = np.zeros([grid_height, grid_width])
values = np.zeros([grid_height, grid_width])
for step in range(num_steps):
    for y in range(grid_height):
        for x in range(grid_width):
            state = np.array([x, y])
            values_actions = np.zeros(actions.shape[0])
            for a, action in enumerate(actions):
                state_prime = state + action
                reward = reward_any
                if np.all(state == state_A):
                    state_prime = state_A_prime
                    reward = reward_A
                elif np.all(state == state_B):
                    state_prime = state_B_prime
                    reward = reward_B
                elif np.any(state_prime < np.array([0, 0])) or np.any(state_prime >= np.array([grid_width, grid_height])):
                    state_prime = state
                    reward = reward_out
                values_actions[a] = reward + gamma * values[state_prime[1], state_prime[0]]
            values_prime[y, x] = np.max(values_actions)
    n = np.linalg.norm(values_prime - values)
    values = np.copy(values_prime)
    if n < n_limit:
        print('converged after {} timesteps'.format(step))
        break
    
print(values)

converged after 96 timesteps
[[21.97690153 24.41877948 21.97690153 19.41877948 17.47690153]
 [19.77884703 21.97690153 19.77884703 17.80096232 16.02086609]
 [17.80096232 19.77884703 17.80096232 16.02086609 14.41877948]
 [16.02086609 17.80096232 16.02086609 14.41877948 12.97690153]
 [14.41877948 16.02086609 14.41877948 12.97690153 11.67884703]]


In [99]:
# example 3.5
num_steps = 100
values = np.zeros([grid_height, grid_width])
for step in range(num_steps):
    values_prime = np.zeros([grid_height, grid_width])
    for y in range(grid_height):
        for x in range(grid_width):
            state = np.array([x, y])
            for action in actions:
                state_prime = state + action
                reward = reward_any
                if np.all(state == state_A):
                    state_prime = state_A_prime
                    reward = reward_A
                elif np.all(state == state_B):
                    state_prime = state_B_prime
                    reward = reward_B
                elif np.any(state_prime < np.array([0, 0])) or np.any(state_prime >= np.array([grid_width, grid_height])):
                    state_prime = state
                    reward = reward_out
                values_prime[y, x] += prob_policy * (reward + gamma * values[state_prime[1], state_prime[0]])
    n = np.linalg.norm(values_prime - values)
    if n < n_limit:
        print('converged after {} timesteps'.format(step))
        break
    values = values_prime
    
print(values)


converged after 39 timesteps
[[ 3.31090387  8.79118019  4.42945778  5.32416158  1.49394036]
 [ 1.52349102  2.99419728  2.25197626  1.90936483  0.54916766]
 [ 0.05272354  0.74004854  0.67495194  0.35998538 -0.40136713]
 [-0.97168967 -0.43361477 -0.35303741 -0.58379676 -1.18128939]
 [-1.85579583 -1.34334742 -1.22741763 -1.42110288 -1.97338525]]
